-- Generated by Sources/export_exp.py. Do not edit by hand.
--
-- One entry per exported clip, lowercased the way OpenMW reports text keys.
--
-- kind is what the clip replaces, and comes from the first word of the group
-- name in its markers: a 'stagger' answers hit1..hit5, a 'death' answers the
-- death groups. A clip is one or the other, never both - each is cut by hand
-- for the job it does. knockdown and knockout are left to the engine.
--
-- bearing is where the clip carries the character, in degrees off their own
-- forward: 0 ahead, +90 their left, 180 back, -90 their right. MEASURED from
-- the source. The names are written from the VIEWER's side - a player
-- looking at the enemy they hit - so a clip called Left carries the body to
-- the viewer's left, which is the character's own right. Back and Forward
-- need no swap.
--
-- tags bucket the same thing, plus "down" for a clip that answers a downward
-- blow - which is not a compass direction and so is readable only in the name.
--
-- far is true for a clip that throws the character a long way, read off the
-- name (Far, or Long). The Lua can save those for the blows that earn them.
return {
    START_KEY = 'start',
    STOP_KEY = 'stop',
    list = {
        { group = 'deathback', kind = 'death', far = false, bearing = 160.7, tags = { back = true } },
        { group = 'deathback1', kind = 'death', far = false, bearing = -178.7, tags = { back = true } },
        { group = 'deathback2', kind = 'death', far = false, bearing = -163.5, tags = { back = true } },
        { group = 'deathbackfar', kind = 'death', far = true, bearing = -165.8, tags = { back = true } },
        { group = 'deathbackfarflip', kind = 'death', far = true, bearing = 174.9, tags = { back = true } },
        { group = 'deathbackhigh', kind = 'death', far = false, bearing = 172.9, tags = { back = true } },
        { group = 'deathbackhighface', kind = 'death', far = false, bearing = -177.8, tags = { back = true } },
        { group = 'deathdown', kind = 'death', far = false, bearing = 131.6, tags = { down = true, left = true } },
        { group = 'deathdownleft', kind = 'death', far = false, bearing = -82.6, tags = { down = true, right = true } },
        { group = 'deathdownleft1', kind = 'death', far = false, bearing = -96.0, tags = { down = true, right = true } },
        { group = 'deathdownleft2', kind = 'death', far = false, bearing = -123.4, tags = { down = true, right = true } },
        { group = 'deathdownright', kind = 'death', far = false, bearing = 110.3, tags = { down = true, left = true } },
        { group = 'deathdownright2', kind = 'death', far = false, bearing = 90.9, tags = { down = true, left = true } },
        { group = 'deathforwardflipfar', kind = 'death', far = true, bearing = -1.3, tags = { forward = true } },
        { group = 'deathforward', kind = 'death', far = false, bearing = -3.4, tags = { forward = true } },
        { group = 'deathleftfar', kind = 'death', far = true, bearing = -98.0, tags = { right = true } },
        { group = 'deathrightfar', kind = 'death', far = true, bearing = 74.8, tags = { left = true } },
        { group = 'deathstepback', kind = 'death', far = false, bearing = -176.6, tags = { back = true } },
        { group = 'deathlongforward', kind = 'death', far = true, bearing = 5.7, tags = { forward = true } },
        { group = 'deathright', kind = 'death', far = false, bearing = 89.3, tags = { left = true } },
        { group = 'deathstepleft', kind = 'death', far = false, bearing = -80.8, tags = { right = true } },
        { group = 'deathwalkleft', kind = 'death', far = false, bearing = -79.5, tags = { right = true } },
        { group = 'staggerback', kind = 'stagger', far = false, bearing = 135.3, tags = { back = true } },
        { group = 'staggerlongleft', kind = 'stagger', far = true, bearing = -90.7, tags = { right = true } },
        { group = 'staggerlongright', kind = 'stagger', far = true, bearing = 90.7, tags = { left = true } },
        { group = 'staggerstumbleback', kind = 'stagger', far = false, bearing = 129.2, tags = { back = true } },
        { group = 'staggerstumbleleft2', kind = 'stagger', far = false, bearing = -77.5, tags = { right = true } },
        { group = 'staggerstumbleright2m', kind = 'stagger', far = false, bearing = 77.5, tags = { left = true } },
        { group = 'staggerstumblehopleft2', kind = 'stagger', far = false, bearing = -89.2, tags = { right = true } },
        { group = 'staggerstumblehopright2', kind = 'stagger', far = false, bearing = 89.2, tags = { left = true } },
        { group = 'staggerstumblerightback', kind = 'stagger', far = false, bearing = 143.7, tags = { back = true } },
        { group = 'staggerstumbleright2', kind = 'stagger', far = false, bearing = 90.5, tags = { left = true } },
        { group = 'staggerstumbleleft2m', kind = 'stagger', far = false, bearing = -90.5, tags = { right = true } },
    },
}
