"""Put the BVH rig into the stored ARP-matching rest pose. Run from Blender.

Open this in the Text Editor and press Run Script, at any time - including
while ARP is in "Redefine Rest Pose" mode, which is the point of it.

ARP unlinks the source rig's action when it enters that mode, so the rest pose
cannot simply be selected from the action list there. This reads the pose out of
"[Rest] ARP Match", writes it straight onto the bones and leaves no action
assigned, so the Apply button sees exactly the pose it needs.

Generated by Sources/bvh_rig_setup.py; re-run that if the rigs change.
"""

import bpy

REST_ACTION = "[Rest] ARP Match"
REST_FRAME = 0


def find_bvh_rig():
    scene_source = bpy.data.objects.get(getattr(bpy.context.scene, "source_rig", ""))
    if scene_source and scene_source.type == "ARMATURE" and "LowerSpineJoint" in scene_source.data.bones:
        return scene_source
    for obj in bpy.data.objects:
        if obj.type == "ARMATURE" and "LowerSpineJoint" in obj.data.bones:
            return obj
    return None


def main():
    rig = find_bvh_rig()
    if rig is None:
        print("[rest-pose] no BVH armature found (looked for a LowerSpineJoint bone)")
        return
    action = bpy.data.actions.get(REST_ACTION)
    if action is None:
        print(f"[rest-pose] no action named {REST_ACTION!r}; run Sources/bvh_rig_setup.py first")
        return

    bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")
    rig.select_set(True)
    bpy.context.view_layer.objects.active = rig

    rig.animation_data_create()
    restore = rig.animation_data.action
    restore_slot = getattr(rig.animation_data, "action_slot", None)
    frame = bpy.context.scene.frame_current

    # Let the action pose the rig, take a copy of the result, then put the rig
    # back the way it was found and write the copy on by hand. Reading the pose
    # rather than the F-curves keeps this working whatever action API the
    # Blender version uses.
    rig.animation_data.action = action
    bpy.context.scene.frame_set(REST_FRAME)
    captured = {pb.name: pb.matrix_basis.copy() for pb in rig.pose.bones}

    rig.animation_data.action = restore
    if restore is not None and restore_slot is not None:
        try:
            rig.animation_data.action_slot = restore_slot
        except (AttributeError, TypeError):
            pass
    bpy.context.scene.frame_set(frame)

    for name, basis in captured.items():
        rig.pose.bones[name].matrix_basis = basis
    bpy.context.view_layer.update()

    print(f"[rest-pose] applied {REST_ACTION!r} to {rig.name!r} "
          f"({len(captured)} bones); action left as {restore.name if restore else 'none'}")


main()
